#!/bin/sh

# set -x # trace shell

# Paraméters

# possible values for sourcespattern
# 0 : no change to filename in sources - 
#		+ you MUST specify a value for "images_parent_folder for -noimages
# 1 : filename stands for filename/filename(.sla)
# 2 : filename stands for filename/PAO/filename(.sla)
# 3 (TODO) : smart detect 2 or 1 or 0

####################################################################
#
# Place for your chapters and book definition
#

# example 1 (replace with your own config)
sources="p_32 PA72/PA72_1 n_8 PA72/PA72_2 n_6 PA72/PA72_3 n_8 p_54"
sourcespattern=0
images_parent_folder="PA72"
output="PA72/PA72"

# example 2 (replace with your own config)
sources="p_1 couv n_3 amisdemax n_8 audrey n_6 ricochet n_8 portail n_6 p_32 PA72 n_22 p_54 hxl n_8 verfeil n_4 repas_1 n_3 p_69"
sourcespattern=1	
output="N72"

####################################################################"
# now managed inside config file :
#
# warning illogic SLA logic	
# FontEmbedding=0	# PDF with embeded or subset fonts
# FontEmbedding=1	# vectorized fonts (no font embeded)
#
####################################################################"
#
# Default options
#

# other user options
setopt=""

pdfwithimages=oui
pdfsuffix=""

#checkpagenum=''
checkpagenum='check'
pagenumwhy='' # reason how start page is set : 'set' by user or 'computed' by script

# Rq : Nb d'éléments d'un array : ${#array[@]}    ou     ${#array[*]}

check='oui'		# '' to not check (only merge chapter pdfs)
vconfig=''
vcheck=''

searched=''	 	# searched string
xmlsearched=''	# xml searched string
nbfound=0

checkcolorall=''
pdfignore=''
getfonts=''
nofontcheck=''

pdfopt=''
vectoopt=''


####################################################################

reset
. shellcolors

while [ "$stopoptions" = "" ]
do
	stopoptions=true

	if  [ "$1" = '-?' ]
	then
		echo "mak makes the global PDF"
		echo "Due to inline config, name of produced PDF is $output.pdf, $output-vecto.pdf or $output-noimages.pdf"
		echo 
		echo "Options :"
		echo "-? : get this help"
		echo "-set : set value to correct value"
		echo "-pagenum : also checks the first page number  of each doc"
		echo "-nopagenum : dont check the first page number of each doc"
		echo "-nocheck : dont check anything, just merge all chapter's pdfs"
		echo '-nofontcheck : dont check fonts'
		echo "-pdfignore : dont create chapters PDFs nor merge them (only checks SLA)"
		echo "-forcepdf : force all pdf (re)creation, even when it exists allready"
		echo "-vconfig : verbose output about config files"
		echo "-vcheck : very verbose output about check"
		echo '-find "word1 or phrase1" : find occurences in all chapters text'
		echo '-xmlfind "string1" : find occurences of string in all chapters SLA file (text + xml tags)'
		echo '-replace "string2" : replace found occurences with specified string2. (with -xmlfind only. with -find still to do)'
		echo '-checkcolorall : check for (bad) uses of "All" named color'
		echo '-getfonts : display embeded fonts'
		echo "-vecto : output to vectorised $output-vecto.pdf - BETA - use twice in a row : mak -vecto -set;mak -vecto"
		echo "-noimages : dont include images in created PDF (souvent à combiner avec -forcepdf)"
		echo
		exit
	fi

	if [ "$1" = "-vconfig" ]
	then
		vconfig=$1
		stopoptions=''
		shift
		break
	fi

	if [ "$1" = "-vcheck" ]
	then
		vcheck=$1
		stopoptions=''
		shift
		break
	fi

	if [ "$1" = "-getfonts" ]
	then
		getfonts=$1
		echo "will output embeded fonts for each .pdf"
		stopoptions=''
		shift
		break
	fi

	if [ "$1" = "-nocheck" ]
	then
		shift
		check=''
		echo "Chapter PDFs will be merged. No check will happen"
		stopoptions=''
		break
	fi

	if [ "$1" = "-nofontcheck" ]
	then
		shift
		nofontcheck="-nofontcheck"
		echo "No font embeding or subseting check will happen"
		stopoptions=''
		break
	fi

	if [ -f .found.tmp ]
	then
		rm .found.tmp
	fi

	if [ "$1" = "-find" ]
	then
		shift
		if [ "$1" = "" ]
		then
			echo "${ESC_error}-find option must have additionnal parameter$ESC_normal"
			exit
		fi
		searched="$1"
		check=''
		pdfignore='-pdfignore'
		stopoptions=''
		shift
		continue
	fi

	if [ "$1" = "-xmlfind" ]
	then
		shift
		if [ "$1" = "" ]
		then
			echo "${ESC_error}-xmlfind option must have additionnal parameter$ESC_normal"
			exit
		fi
		xmlsearched="$1"
		check=''
		pdfignore='-pdfignore'
		stopoptions=''
		shift
		continue
	fi

	if [ "$1" = '-checkcolorall' ]
	then
		checkcolorall='yes'
		xmlsearched="COLOR=\"All\""
		check=''
		pdfignore='-pdfignore'
		stopoptions=''
		shift
		continue
	fi

	if [ "$1" = "-replace" ]
	then
		if [ "$xmlsearched" = "" ] && [ "$searched" = "" ]
		then 
			echo "${ESC_error}-replace option must follow some -xmlfind or -find option. No such options found here.$ESC_normal"
			exit
		fi
		shift
		if [ "$1" = "" ]
		then
			echo "${ESC_error}-replace option must have additionnal parameter$ESC_normal"
			exit
		fi
		replaced="$1"
		shift
		echo "Replace all found strings with '$replaced'"
		stopoptions=''
		continue
	fi

	if [ "$1" = "-set" ]
	then
		shift
		setopt='-set'
		stopoptions=''
		pdfignore='-pdfignore'
		continue
	fi

	if [ "$1" = "-pdfignore" ]
	then
		shift
		pdfignore='-pdfignore'
		stopoptions=''
		continue
	fi

	if [ "$1" = "-forcepdf" ]
	then
		shift
		pdfignore=''
		pdfopt='-forcepdf'
		stopoptions=''
		continue
	fi

	if [ "$1" = "-vecto" ]
	then
		shift
		vectoopt='-vecto'	# pour slacheck et en suffixe de output
		output="$output$vectoopt"
		stopoptions=''
		continue
	fi

	if [ "$1" = "-nopagenum" ]
	then
		shift
		checkpagenum=''
		stopoptions=''
		continue
	fi
	
	if [ "$1" = "-noimages" ]
	then
		pdfsuffix=$1
		shift
		pdfwithimages='no'
		pdfopt='-forcepdf'
		stopoptions=''
		continue
	fi

done

####################################################################"
verboseopt="$vconfig $vcheck"

listepdf=""
pagenumopt=''

numpagecourant=1
for fic in $sources
do 
	if [ "${fic#p_}" != "$fic" ] && [ $checkpagenum = 'check' ]
	then
		numpageset=${fic#p_}
		if [ "$lastpagenumwhy" = computed ] && [ $numpageset != $numpagecourant ]
		then
			echo "${ESC_warning} or error : After adding pages, page num should be $numpagecourant, but is set to $numpageset"
			echo "Continuing.$ESC_normal"
		fi
		numpagecourant=$numpageset
		pagenumopt="-pagenum $numpagecourant"
		echo "Début page $numpagecourant"
		pagenumwhy=set
		continue
	fi

	if [ "${fic#n_}" != "$fic" ] && [ $checkpagenum = 'check' ]
	then
		numpagecourant=$(( $numpagecourant+${fic#n_} ))
		pagenumopt="-pagenum $numpagecourant"
		echo "${fic#n_} pages"
		pagenumwhy=computed
		continue
	fi

	# images_parent_folder : dossier contenant le  SLA, sans / final
	if [ "$sourcespattern" = 1 ]
	then
		images_parent_folder="$fic"
		fic="$fic/$fic"
	elif [ "$sourcespattern" = 2 ]
	then 
		images_parent_folder="$fic/PAO"
		fic="$fic/PAO/$fic"
	elif [ "$images_parent_folder" = "" ]
	then 
		images_parent_folder="."
	fi

	if [ ! -f "$fic.sla" ] 
	then 
		echo Error : missing $fic.sla file 
# il faut pas exit pour PA composite
#		exit
	fi

	echo
	echo -n $fic
	[ "$pagenumopt" != "" ] && echo " : page $numpagecourant ($pagenumwhy)"
	[ "$pagenumopt" = "" ] && echo "${ESC_error}no starting page ?$ESC_normal"
	lastpagenumwhy=$pagenumwhy
	pagenumwhy=''

	if [ "$searched" != '' ] || [ "$xmlsearched" != '' ]
	then
		# Enlever d'abord les césures avant de chercher $searched, et même $xmlsearched
		# césures conditionnelles = caractère Unicode U+00AD
		# http://stackoverflow.com/questions/8562354/remove-unicode-characters-from-textfiles-sed-other-bash-shell-methods
		# La commande `echo -ne '\u00AD' | xxd` donne c2ad qu'il faut utiliser avec \x dans `sed 's/...'` = 
		cleansla="$fic.clean.sla"
		sed -e 's/\xc2\xad//g' "$fic.sla" > "$cleansla"
	fi

	if [ "$searched" != '' ]
	then
		count=`grep -i "<ITEXT[^>]*CH=" "$cleansla" | grep -c -o -i "\"[^\"]*$searched[^\"]*\""`
		echo Search for "$searched" : $count results
		if [ "$count" != "0" ]
		then
			nbfound=$(( $nbfound+$count ))

			echo $ESC_yellow
			grep -ni "<ITEXT[^>]*CH=" "$cleansla" | grep -i "\"[^\"]*$searched[^\"]*\"" | sed -e 's/<ITEXT[^>]*CH="//' | sed -e 's/"\/>//'
			echo $ESC_normal
			
			# -n : line number
			# /dev/null is added so grep believes there is more than one file and outputs the filename
			grep -ni "<ITEXT[^>]*CH=\"[^\"]*$searched[^\"]*\"" "$cleansla" /dev/null | sed -e 's/<ITEXT[^>]*CH="//' | sed -e 's/"\/>//' >> .found.tmp
		fi
		rm $cleansla
	fi
	
	if [ "$xmlsearched" != '' ]
	then
		# FIXME ? : malgré les -i ça n'a pas l'air case-insensitif
		count=`grep -c -o -i "$xmlsearched" "$cleansla"`
		echo Search for "$xmlsearched" : $count results
		if [ "$count" != "0" ]
		then
			nbfound=$(( $nbfound+$count ))

			echo $ESC_yellow
			grep -ni "$xmlsearched" "$cleansla"
			echo $ESC_normal
			
			# -n : line number
			# /dev/null is added so grep believes there is more than one file and outputs the filename
			grep -ni "$xmlsearched" "$cleansla" /dev/null >> .found.tmp
			
			echo "replaced=$replaced"
			if [ "$replaced" != '' ]
			then
				if [ -f "$fic.before_replace.sla" ]
				then
					echo "$fic.before_replace.sla allready exists : moved as .bak"
					mv "$fic.before_replace.sla" "$fic.before_replace.sla.bak"
				fi
				cp "$fic.sla" "$fic.before_replace.sla"
				echo $fic.sla is saved into $fic.before_replace.sla
				echo $xmlsearched is replaced with $replaced in $fic.sla 
				echo sed -i -- \""s/$xmlsearched/$replaced/g"\" "$fic.sla"
				sed -i -- \""s/$xmlsearched/$replaced/g"\" "$fic.sla"
			fi
		fi
		rm $cleansla
	fi

	if [ "$pdfwithimages" = "no" ]
	then
		mv -b "$images_parent_folder/images" "$images_parent_folder/images.bak"
		mv -b $fic.pdf "$fic"avecimages.pdf
		ls $images_parent_folder
#		exit; # XXX
	fi

	if [ "$check" = "oui" ] 
	then
		echo "slacheck $vectoopt $setopt $pagenumopt $pdfopt $nofontcheck $pdfignore $verboseopt $fic"
		slacheck $vectoopt $setopt $pagenumopt $pdfopt $nofontcheck $pdfignore $verboseopt $fic
		echo "slacheck done"
	fi

	if [ "$pdfwithimages" = "no" ]
	then
		mv -b "$images_parent_folder/images.bak" "$images_parent_folder/images"
		mv -b $fic.pdf "$fic$pdfsuffix".pdf
		mv -b "$fic"avecimages.pdf $fic.pdf
	fi

	if [ "$getfonts" != '' ]
	then
		# alternative : `strings yourPDFfilepath.pdf | grep FontName`
		echo "pdffonts $fic.pdf"
		pdffonts "$fic.pdf"
	fi

	listepdf="$listepdf $fic$pdfsuffix.pdf"
done

if [ "$pdfignore" = "-pdfignore" ] || [ "$pdfignore" = "pdfignore" ]
then
	exit
fi


if [ "$pdfignore" = "" ]
then
	mv $output$pdfsuffix.pdf $output$pdfsuffix.pdf.bak

	# add some special file as a last page cover
	# listepdf="$listepdf separettes/p68-HR.pdf"
	echo "Merged PDFs : $listepdf"
	echo "Avec /usr/bin/pdftk"
	# sur ubuntu 18.04 pdftk n'est plus dispo et déclanchait une erreur en snap
	# la commande suivante a réparé cela
	# sudo ln -s /snap/pdftk/current/usr/bin/pdftk /usr/bin/pdftk
	# à condition qu'on l'appelle en absolu :
	/usr/bin/pdftk $listepdf cat output $output$pdfsuffix.pdf

	# sinon on peut le faire avec sejda
	# echo "Avec sejda-console (http://sejda.org/)"
	# sejda-console merge -f $listepdf -o $output$pdfsuffix.pdf

	if [ -f $output$pdfsuffix.pdf  ] 
	then
		ls -ltr $output$pdfsuffix.pdf 
		echo $output$pdfsuffix.pdf created OK  
		evince $output$pdfsuffix.pdf &
	fi
fi

# création d'une version sans marge (marges enlevées à l'arrache pour l'instant) : 
# un peu utile pour impression un peu plus grand en pleine page
# pdfcrop --margins '-25 -25 -25 -25' $output.pdf normargin_$output.pdf
# [ -f normargin_$output.pdf  ] && evince normargin_$output.pdf & ls -ltr normargin_$output.pdf ; echo normargin_$output.pdf created OK

if [ "$searched$xmlsearched" != '' ]
then
	echo Done
	echo 
	echo ${ESC_yellow}Searching \'$searched$xmlsearched\' :  $nbfound results found in whole book$ESC_normal
	if [ $nbfound != 0 ]
	then
		if [ "$checkcolorall" != '' ]
		then
			echo "${ESC_error}Some (bad) uses of COLOR=\"All\" have been found !$ESC_normal"
		fi
		cat .found.tmp
	fi
fi

if [ "$getfonts" != '' ]
then
	pdffonts $output$pdfsuffix.pdf
fi
