#!/bin/bash

# version 0.2.1 - 6 avril 2015
# todo : option to detect inline images, option to detect empty image frames

filename=""
filenameoption="--include=*.sla"
folderexcludeoption="--exclude-dir=archives"
recurseoption="-r"
stopoption=""

while [ "$stopoptions" = "" ] && [ "$1" != "" ]
do
	case $1 in 
	"-h" | "-?" )
		echo "usage : slacheckimages [-h] [-r] [-e pattern] [scribusfile]"
		echo "checks whether all used images are stored in scribusfile's 'images' subfolder"
		echo options :
		echo -h or -? : displays this help
		echo "-r : recurse folders (default)"
		echo "-e pattern : exclude files matching pattern (default : archives)"
		echo "scribusfile : specific file to check. Dont use with -r"
		echo "-v : verbose (displays more details)"
		echo
		exit
		;;

	"-v")
		shift
		verbose=oui
		;;
		
	"-r" )
		shift
		recurseoption="-r"
		filenameoption="--include=*.sla"
		;;

	"-e" )
		if [ "$2" = "" ]
		then
			echo Error : -e option without pattern to exclude folders
			exit
		fi
		folderexcludeoption="--exclude-dir=$2"
		shift
		shift
		;;
	
	*) 	if [ ! -f "$1.sla" ]
		then
			if [ ${1##*\.} = "sla" ] # ${parameter##pattern} : enleve le début jusqu'au dernier pattern
			then
				echo "Error : you should not specify the sla extension in the filename"
			fi
			echo "Error : file \"$1.sla\" doesn't exist"
			exit
		fi
		filename="$1.sla"
		filenameoption=""
		folderexcludeoption=""
		recurseoption=""
		stopoptions=true
		shift
		;;
	esac
done

if [ "$1" != "" ]
then
	echo "Error : too many parameters"
	exit
fi

if [ "$verbose" = "oui" ]
then
	# verbose shell + expand variables (set -v : verbose with no expand)
	set -x
fi

# PFILES="images/ : image is stored in correct images subfolder
# PFILES="" : empty image frame OR inline image
alloptions="-H $recurseoption $folderexcludeoption $filenameoption"
grep $alloptions -- PFILE= "$filename" | grep -v 'PFILE="images/\|PFILE=""' | sed 's/^\(.*\.sla\).* PFILE="\([^"]*\)".*$/In \1, image has source file outside \/images : \2/'

