#!/bin/sh

#
# use : slacheckattr slafile tag attribute value [comment]
# Checks the the value of some attribute for a specified tag in scribus file
# 
# todo : use xmlstarlet to update value of an attribute 
# cf http://xmlstar.sourceforge.net/doc/UG/xmlstarlet-ug.html#d0e461
# xml ed -u "/xml/table/rec[@id=3]/@id" -v 5 xml/tab-obj.xml
#

while [ "$stopoptions" = "" ] 
do
	case $1 in 
	"-h" | "-?" )
		shift
		echo Usage : slacheckattr [-h] [-v] [-all] slafile tag attribute value [comment]
		echo Action : looks in \'slafile\'.SLA for \'tag\'\'s \'attribute\' value
		echo and issues a warning begining with \'comment\' when the found value is different than \'value\'.
		echo Options :
		echo -h, -? : display this help
		echo -v : verbose
		echo -all : all 'tag' tags should be checked and have the same stated attribute value. 
		echo -all option is required to check PAGE attributes, since there are many PAGEs in a document.
		exit
		;;

	"-v")
		shift
		verbose=oui
		;;

	"-all")
		shift
		all=oui
		;;
		
	"-get")
		shift
		get=oui
		;;

	*) stopoptions=true	;;
	esac
done

if [ $# -lt 3 ]
then 
	echo error : missing document, tag or attribute parameter\(s\). See with -h option first.
	exit
fi

if  [ "$4" = "" ] && [ "$get" = "" ]
then 
	echo error : missing value parameter\(s\). See with -h option first.
	exit
fi

#  ext=${filename##*\.} donne l'extension si on voulait gérer $1 "avec ou sans" extension SLA
if [ ! -f $1.sla ]
then
	echo "Error : file \"$3\" doesn't exist"
	exit
fi

# found=`xmllint --xpath "//$2/@$3" $1.sla | sed -e 's/^ *//' -e 's/ *$//'`
found=`xmllint --xpath "//$2/@$3" $1.sla | strtrim`

if  [ "$get" = "oui" ]
then
	echo $found
	exit
fi

expected="$3=\"$4\""
if [ "$verbose" = "oui" ]
then
	echo \* In $1.sla, check whether \<$2 $expected
	echo \* xmllint renvoie `xmllint --xpath "//$2/@$3" $1.sla`
	echo \* Found : $found
fi

# echo compare "$found"
# echo avec... "$3=\"$4\""
# echo 

if [ "$found" = "" ]
then
	echo 
	echo Error \<$2 $3=\"$4\" not found in $1.sla \(xmllint renvoie  `xmllint --xpath "//$2/@$3" $1.sla`\)
	exit
elif [ "$all" = "oui" ]
then
	for one in $found
	do
		if [ "$verbose" = "oui" ]
		then echo found : $one
		fi
		if [ $one != $expected ]
		then echo $3 NOT OK ! In $1.sla, found \<$2 $one\> \(expected value for $3 is $expected\)
		fi
	done
elif [ "$found" != "$expected" ]
	then echo $3 NOT OK ! In $1.sla, found \<$2 `xmllint --xpath "//$2/@$3" $1.sla`\> \(expected value for $3 is $4\)
fi
