#!/bin/bash

# slacheckfonts 

# v0.3 : no more buggy -vecto option
# v0.2 : tests whether all used fonts are either embeded or subset=vectorized

# TODO : detect fonts that are used in unused styles definitions and dont warn about them or with special message.

if [ "$1" = "-?" ] || [ "$1" = "-h" ] || [ "$1" = "" ]
then
	echo "Usage : slacheckfont [-h] [-v] scribusfile"
	echo "Checks whether all used fonts are either embeded or subset in scribusfile.sla"
	echo "Options (order matters) :"
	echo -h displays this help
	echo -v displays details
	exit
fi

if [ "$1" = "-v" ]
then
	verbose=oui
	shift
fi

vecto=""
if [ "$1" = "-vecto" ]
then
	vecto="-vecto"
	shift
elif [ "$1" = "-novecto" ]
then
	vecto="-novecto"
	shift
fi

if [ "$1" = "" ]
then
	echo Error : scribus file argument missing
	exit
fi

[ ! -f "$1.sla" ] && echo Error : missing $1.sla file && exit

# Liste of all fonts uses
#
# Possible fonts uses are :
#   <ITEXT FONT="Arimo Regular" CH=" "/>
#	<CHARSTYLE CNAME="Default Character Style" DefaultStyle="1" FONT="Liberation Sans Regular" FONTSIZE="8.8" FCOLOR="Black"/>
#	<STYLE NAME="NoteSignature" PARENT="Signature" FONT="Liberation Sans Regular"/>
#	<tab FONT="Wingdings Regular" FONTSIZE="15"/>
#
# s/regexp/replacement/
# ! The replacement may contain the special character & to refer to that portion of the pattern which matched

# looking for fontnames contained in all FONT="..."
# excluding <STYLE and <STYLENAME uses that are style definitions, not uses
used=`grep -v '^\s*<CHARSTYLE ' $1.sla | grep -v '^\s*<STYLE ' | grep " \(FONT\|DFONT\)=\"[^\"]*\"" | sed -e 's/^.* FONT=\(\"[^\"]*\"\).*$/\1/' | sed -e 's/^.* DFONT=\(\"[^\"]*\"\).*$/\1 in <DOCUMENT ...>/'`
#
# Embeded fonts : 	<Fonts Name="CC Icons Regular"/>
# Subseted fonts : 	<Subset Name="Arimo Regular"/>
managed=`sed -n '/\(<Fonts \|<Subset \)/p' $1.sla | sed 's/.*Name=\(\"[^\"]*\"\).*$/\1/'`

errormessage="font is neither vectorized nor embeded"

if [ "$verbose" = oui ]
then
	echo Embeded or subset fonts are : $managed
	echo Used fonts are : $used
fi

IFS=$'\n'
for usedfont in $used
do 
	recognised=""
	errored=""
	for managedfont in $managed
	do
		if [ "$usedfont" = "$managedfont" ]
		then recognised=oui;
		fi
	done
	if [ "$recognised" = "" ]
	then 
		echo -e "${ESC_error} in $1.sla with $usedfont : $errormessage${ESC_normal}"
		errored=oui;
	fi
done

if [ "$verbose" = "oui" ] && [ "$errored" = "" ]
then echo "${ESC_green}No font error has been found${ESC_normal}"
fi

exit
