#!/bin/bash

# slacheckfonts 

# v0.3 : no more buggy -vecto option
# v0.2 : tests whether all used fonts are either embeded or subset=vectorized

# TODO : detect fonts that are used in unused styles definitions and dont warn about them or with special message.

if [ "$1" = "-?" ] || [ "$1" = "-h" ] || [ "$1" = "" ]
then
	echo "Usage : slacheckfont [-h] [-v] scribusfile"
	echo "Checks whether all used fonts are either embeded or subset in scribusfile.sla"
	echo "Options (order matters) :"
	echo -h displays this help
	echo -v displays details
	exit
fi

if [ "$1" = "-v" ]
then
	verbose=oui
	shift
fi

vecto=""
if [ "$1" = "-vecto" ]
then
	vecto="-vecto"
	shift
elif [ "$1" = "-novecto" ]
then
	vecto="-novecto"
	shift
fi

if [ "$1" = "" ]
then
	echo Error : scribus file argument missing
	exit
fi

[ ! -f "$1.sla" ] && echo Error : missing $1.sla file && exit

# Liste of all fonts uses
#
# Possible fonts uses are :
#   <ITEXT FONT="Arimo Regular" CH=" "/>
#	<CHARSTYLE CNAME="Default Character Style" DefaultStyle="1" FONT="Liberation Sans Regular" FONTSIZE="8.8" FCOLOR="Black"/>
#	<STYLE NAME="NoteSignature" PARENT="Signature" FONT="Liberation Sans Regular"/>
#	<tab FONT="Wingdings Regular" FONTSIZE="15"/>
#
# s/regexp/replacement/
# ! The replacement may contain the special character & to refer to that portion of the pattern which matched
used=`grep " FONT=\"[^\"]*\"" $1.sla | sed -e 's/^.* FONT=\(\"[^\"]*\"\).*$/\1/'`
#
# Embeded fonts : 	<Fonts Name="CC Icons Regular"/>
# Subseted fonts : 	<Subset Name="Arimo Regular"/>
known=`sed -n '/\(<Fonts \|<Subset \)/p' $1.sla | sed 's/.*Name=\(\"[^\"]*\"\).*$/\1/'`
errormessage="font is neither vectorized nor embeded"

# known=`sed -n '/\(<Fonts \|Subset \)/p' $1.sla | sed 's/.*Name=\(\"[^\"]*\"\).*$/\1/'`

if [ "$verbose" = oui ]
then
	echo Embeded or subset fonts are : $known
	echo Used fonts are : $used
fi

IFS=$'\n'
for usedfont in $used
do 
	recognised=""
	errored=""
	for knownfont in $known
	do
		if [ "$usedfont" = "$knownfont" ]
		then recognised=oui;
		fi
	done
	if [ "$recognised" = "" ]
	then 
		echo "\033[1;31mError in $1.sla\033[0m with '$usedfont' : $errormessage"
		errored=oui;
	fi
done

if [ "$verbose" = "oui" ] && [ "$errored" = "" ]
then echo "No font error has been found"
fi

exit
