#!/bin/bash

#set -x  # for a detailed trace

# use : slasync master dest

# $1 : fichier sla master pour les styles 
# $2 : fichier sla à synchroniser
# tous 2 SANS l'extension .SLA
# ext=${filename##*\.} donne l'extension si on voulait gérer $1 "avec ou sans" extension SLA

. shellcolors

while [ "$stopoptions" = "" ] 
do
	stopoptions=true
	
	if  [ "$1" = '-?' ]; then
		echo "use : `slasync <options> masterfile.sla chapterfile.sla`"
		echo "Replaces all paragraph styles and character styles of chapterfile.sla by those in masterfile.sla"
		echo "options :"
		echo "-s : replaces all styles"
		echo "-ps : replaces paragraph styles only"
		echo "-cs : replaces character styles only"
		echo "-m : replaces masterpages"
		echo "-c : replaces colors"
		echo "-a : replaces paragraph and character styles, colors and masterpages"
		echo "-nodes <node1|node2|node3> : replaces all nodes specified in pipe separated list"
		echo "-keeps <str> : keeps paragraph and character style definitions whose NAME contains <str> string in chapter. These MUST NOT be defined in master"
		echo "-trace : displays styles kept in chapter and nodes import-forced from master"
		exit
	elif [ "$1" = '-nodes' ]; then
		shift
		if [ "$1" = "" ]; then
			echo -e "${ESC_error} missing <node> after -nodes option"
			exit
		fi
		nodes=$1
	elif [ "$1" = '-keeps' ]; then
		shift
		if [ "$1" = "" ]; then
			echo -e "${ESC_error} missing <part> after '-keeps' option. Read the doc with -? option"
			exit
		fi
		keeps="$2"
		echo "keeps char and par styles with NAME containing '$2'"
		shift
		stopoptions=''
	elif [ "$1" = "-s" ]; then
		nodes="STYLE|CHARSTYLE"
		shift
	elif [ "$1" = "-ps" ]; then
		nodes=STYLE
		shift
	elif [ "$1" = "-cs" ]; then
		nodes=CHARSTYLE
		shift
	elif [ "$1" = "-m" ]; then
		nodes=MASTERPAGE
		shift
	elif [ "$1" = "-c" ]; then
		nodes=COLOR
		shift
	elif [ "$1" = "-a" ]; then
		nodes="STYLE|CHARSTYLE|COLOR|MASTERPAGE"
		shift
	elif [ "$1" = "-trace" ]; then
		trace=true
		shift
		stopoptions=''
	fi
done

if [ "$1" = "" ]; then
	echo -e "${ESC_error} missing masterpage in slasync command. Read doc using -?"
	exit
elif [ ! -f "$1.sla" ]; then
	echo -e "${ESC_error} in slasync command : file \"$1.sla\" doesnt exist. Read doc using -?"
	exit
elif [ "$2" = "" ] ; then
	echo -e "${ESC_error} missing chapter file in slasync command. Read doc using -?"
	exit
elif [ ! -f "$2.sla" ]; then
	echo -e "${ESC_error} in slasync command : file \"$2.sla\" doesnt exist. Read doc using -?"
	exit
elif [ "$2" = "$3" ]; then
	echo -e "${ESC_error} chapter and master are identical"
	exit
fi

cp -f $2.sla $2.bak.sla
master=$1.sla
chapter=$2.sla

# xmlstarlet ed -u ... -v ... : update value of path to be value (-v) or other xpath value (-x)
#	ne change pas les attributs des xpaths mais affecte leurs valeurs
#
# xmlstarlet ed -d ... : delete ; -i -t ... -v ... : insert
#
# xmlstarlet ed -d "SCRIBUSUTF8NEW/DOCUMENT/STYLE" fic.sla : retire toutes les définitions de parstyles
# 
#
# xmlstarlet sel -t -v "count(/SCRIBUSUTF8NEW/DOCUMENT/COLOR)" vide.sla
# 	renvoie le nombre de couleurs définies
# xmlstarlet sel -t -m "SCRIBUSUTF8NEW/DOCUMENT/COLOR" -c . -n vide.sla
# 	renvoie la liste de toutes les couleurs : <COLOR NAME="Black" SPACE="CMYK" C="0" M="0" Y="0" K="100"/>\n<COLOR NAME="Blue"... etc
#	"-m" : match XPATH ; "-c ." : echoes copy of XPATH expression et "-n" : echoes EOL

# Insérer des composants sur mesure : 
# echo "<x/>" | xml sel -t -m / -e xml -e child -a data -o value
# produces :
# <xml><child data="value"/></xml>
# -m / : se mettre à la racine
# -e xml : output <xml> et se mettre dedans
# -e child : output <child> et se mettre dedans
# -a data -o value : ajouter un attribut data avec la valeur value
#
# autres xpaths :
# '/xml/block/el[@name="b"]' : ceux dont l'attribut 'name' a la valeur 'b'
# '/xml/block/el[not(@name)]' : ceux qui n'ont pas d'attribut 'name'

# Capture chapter's kept nodes
if [ "$keeps" != "" ]; then
	xmlstarlet sel -t -m "SCRIBUSUTF8NEW/DOCUMENT/STYLE[contains(@NAME,'$keeps')]" -c . -n $chapter > ".$chapter.kept_$nodes.xml"
	xmlstarlet sel -t -m "SCRIBUSUTF8NEW/DOCUMENT/CHARSTYLE[contains(@NAME,'$keeps')]" -c . -n $chapter >> ".$chapter.kept_$nodes.xml"
	if [ $trace != "" ]; then
		echo
		echo "Kept in $chapter :"
		cat ".$chapter.kept_$nodes.xml"
	fi
fi

# Capture master's nodes
xmlstarlet sel -t -m "SCRIBUSUTF8NEW/DOCUMENT" -m $nodes -c . -n $master > ".$master.$nodes.xml"

if [ $trace != "" ]; then
	echo
	echo "Found in master $master :"
	cat ".$master.$nodes.xml"
fi

# Empty chapter nodes
xmlstarlet ed -d "SCRIBUSUTF8NEW/DOCUMENT/$nodes" $chapter > ".$chapter.without_$nodes.xml"

# Insert master nodes at the begining of the <DOCUMENT>
sed "/<DOCUMENT.*>/ r .$master.$nodes.xml" ".$chapter.without_$nodes.xml" > result.sla
# Insert kept nodes
sed "/<DOCUMENT.*>/ r .$chapter.kept_$nodes.xml" result.sla > result.sla

